config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'members#index'
  resources :users, only: [:show]
  resources :members do
    resources :posts
    resources :comments, only: [:index, :create] 
  end
  resources :items, only: [:index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :member

  validates :comment,        presence: true
  validates :comment_member, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :posts

  validates :name, presence: true
  validates :price, presence: true,
  numericality: { only_integer: true, less_than_or_equal_to: 9_999_999, allow_blank: true }, format: { with: /\A[0-9]+\z/, allow_blank: true }
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :comments
  has_one_attached :image

  validates :name,  presence: true
  validates :fixed, presence: true
  validates :color, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :item
  belongs_to :user
  belongs_to :member
  has_many :comments

  validates :day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :items
  has_many :posts
  has_many :comments

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX
  validates :family_name,        presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @members = Member.includes(:user)
    @member = Member.find(params[:member_id])
    @comments = @member.comments.includes(:user).order('id DESC')
    @comment = Comment.new
    unless @member.user_id == current_user.id
      redirect_to root_path
    end
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to request.referer
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :comment_member).merge(user_id: current_user.id, member_id: params[:member_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render action: :new
    end
  end

  def show
    unless @item.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def edit
    unless @item.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    if @item.update(item_params)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member, only: [:show, :edit, :update]

  def index
    @members = Member.includes(:user)
  end

  def show
    unless @member.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to root_path
    else
      render action: :new
    end
  end

  def edit
    unless @member.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    if @member.update(member_params)
      redirect_to member_post_path(@member.id)
    else
      render action: :edit
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :fixed, :color, :image).merge(user_id: current_user.id)
  end

  def set_member
    @member = Member.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member
  before_action :set_month
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @members = Member.includes(:user)
    @items = Item.includes(:user)
    @post = Post.new
    
  end

  def show
    @members = Member.includes(:user)
    @items = Item.includes(:user)
    @post = Post.new
    @posts = @member.posts.includes(:user).order('day DESC').where(day: @month.all_month)
    posts_sum
    @comments = @member.comments.includes(:user).order('id DESC').limit(5)
    
    unless @member.user_id == current_user.id
      redirect_to root_path
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = @member.posts.new(post_params)
    if @post.save
      redirect_to request.referer
    end
  end

  def edit
    unless @member.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    if @post.update(post_params)
      redirect_to action: :show
    else
      render action: :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to action: :show
  end

  private

  def post_params
    params.require(:post).permit(:day, :item_id).merge(user_id: current_user.id, member_id: @member.id)
  end

  def set_member
    @member = Member.find(params[:member_id])
  end

  def set_month
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @prev_month = @month.prev_month
    @next_month = @month.next_month
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def posts_sum
    @posts_sum = 0
    @posts.each do |post|
      @posts_sum += Item.find_by(id: post.item_id).price
    end
    @posts_sum_total = @member.fixed + @posts_sum
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_new.html.erb
<section id='comment-new' class='contents-section'>
  <%= form_with model: [@member, @comment], id: "comment-form", class: "comment-member-wrap" do |f| %>
    <%= f.collection_select :comment_member, current_user.members.all, :id, :name, include_blank: "コメントするひと" %>
    <%= f.text_field :comment , class: "comment-form-text", placeholder: 'コメントをかく'%>
    <%= f.submit "コメントをする", id: "comment-form-submit", class: "comment-form-submit", style: "background: #{@member.color};" %>
  <% end %>
  </section>

app/views/comments/_show.html.erb
<h3 class='post-ttl' style='color: <%= @member.color %>;'>
  <span class="member-ttl-name" style='border-bottom: 2px dotted <%= @member.color %>'>コメント(さいしん5けん)</span>
</h3>
<ul id="comments">
<% @comments.each do |comment| %>
  <li class="comment">
    <%= link_to member_post_path(comment.comment_member), class: 'comment-member-link'  do %>
      <div class='comment-img'>
        <%= image_tag Member.find_by(id: comment.comment_member).image %>
      </div>
      <p class="comment-name" style='color: <%= Member.find_by(id: comment.comment_member).color %>;'><%= Member.find_by(id: comment.comment_member).name %></p>
    <% end %>
    <p class="comment-date" style='color: <%= Member.find_by(id: comment.comment_member).color %>;'><%= comment.created_at.strftime('%Y.%m.%d') %><br><%= comment.created_at.strftime('%H:%M:%S') %></p>
    <p class="comment-text" style='color: <%= Member.find_by(id: comment.comment_member).color %>;'><%= comment.comment%></p>
  </li>
<% end %>
  <li class="comment comment-pockeee">
    <div class='comment-img'>
      <%= image_tag 'pockeee.png' %>
    </div>
    <p class="comment-name">ポッケー</p>
    <p class="comment-date"><%= @member.created_at.strftime('%Y.%m.%d') %><br><%= @member.created_at.strftime('%H:%M:%S') %></p>
    <p class="comment-text">おうちの おてつだいを おうえんするよ！がんばってね！</p>
  </li>
  <li class="comment comment-pockeee">
    <div class='comment-img'>
      <%= image_tag 'pockeee.png' %>
    </div>
    <p class="comment-name">ポッケー</p>
    <p class="comment-date"><%= @member.created_at.strftime('%Y.%m.%d') %><br><%= @member.created_at.strftime('%H:%M:%S') %></p>
    <p class="comment-text">ポッケーへようこそ</p>
  </li>
</ul>

app/views/comments/index.html.erb
<div class="contents-wrap">
  <section id="comments-coments" class="contents-section">
    <div class="contents-section-inner">
      <h3 class="post-ttl" style='color: <%= @member.color %>;'>
        <span class="member-ttl-name" style='border-bottom: 2px dotted <%= @member.color %>'>コメント</span>
      </h3>
      <%= render "comments/new" %>
      <ul id="comments">
      <% @comments.each do |comment| %>
        <li class="comment">
          <%= link_to member_post_path(id: comment.comment_member), class: 'comment-member-link'  do %>
            <div class='comment-img'>
              <%= image_tag Member.find_by(id: comment.comment_member).image %>
            </div>
            <p class="comment-name" style='color: <%= Member.find_by(id: comment.comment_member).color %>;'><%= Member.find_by(id: comment.comment_member).name %></p>
          <% end %>
          <p class="comment-date" style='color: <%= Member.find_by(id: comment.comment_member).color %>;'><%= comment.created_at.strftime('%Y.%m.%d') %><br><%= comment.created_at.strftime('%H:%M:%S') %></p>
          <p class="comment-text" style='color: <%= Member.find_by(id: comment.comment_member).color %>;'><%= comment.comment%></p>
        </li>
      <% end %>
        <li class="comment comment-pockeee">
          <div class='comment-img'>
            <%= image_tag 'pockeee.png' %>
          </div>
          <p class="comment-name">ポッケー</p>
          <p class="comment-date"><%= @member.created_at.strftime('%Y.%m.%d') %><br><%= @member.created_at.strftime('%H:%M:%S') %></p>
          <p class="comment-text">おうちの おてつだいを おうえんするよ！がんばってね！</p>
        </li>
        <li class="comment comment-pockeee">
          <div class='comment-img'>
            <%= image_tag 'pockeee.png' %>
          </div>
          <p class="comment-name">ポッケー</p>
          <p class="comment-date"><%= @member.created_at.strftime('%Y.%m.%d') %><br><%= @member.created_at.strftime('%H:%M:%S') %></p>
          <p class="comment-text">ポッケーへようこそ</p>
        </li>
      </ul>
    </div>
  </section>
</div>    

app/views/items/_form.html.erb
<%= form_with model: @item, url: items_path, id: 'new-item', class: 'item-form-wrap', local: true do |f|%>
  <div class='form-wrap'>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">おてつだい項目名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, class: "input-default", id:"item-name", placeholder:"そうじき・おさらふきなど" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">金額(半角)</label>
        <span class="indispensable">必須</span>
      </div>
      <div class='form-input-wrap'>
        <%= f.text_field :price, class: "input-default input-custom", id:"item-price", placeholder:"例）300" %>
        <span class="form-yen">円(えん)</span>
      </div>
    </div>
    <div class="item-save-btn-wrap">
      <%= f.submit "保存する", class: "item-save-btn" %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class='contents'>
  <section class="contents-section">
    <div class="contents-section-inner">
      <h1 class='page-ttl'><span>おてつだい編集<span></h1>
      <%= form_with model: @item, id: 'new-item', class: 'item-form-wrap', local: true do |f|%>
      <div class='form-wrap'>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">おてつだい項目名</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :name, class: "input-default", id:"item-name", placeholder:"そうじき・おさらふきなど" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">金額(半角)</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='form-input-wrap'>
            <%= f.text_field :price, class: "input-default input-custom", id:"item-price", placeholder:"例）300" %>
            <span class="form-yen">円(えん)</span>
          </div>
        </div>
        <div class="item-save-btn-wrap">
          <%= f.submit "保存する", class: "item-save-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/items/index.html.erb
<div class='contents'>
  <section class="contents-section">
    <div class="contents-section-inner">
      <h2 class='page-ttl'><span class='member-ttl-name'><%= current_user.family_name %><span class='member-ttl-name-small'>さんちの</span>おてつだいリスト</span></h2>
      <table class='item-list-wrap'>
        <tr>
          <th>項目名</th>
          <th>金額</th>
          <th>編集</th>
        </tr>
        <% current_user.items.each do |item| %>
        <tr>
          <td class='item-list-name'><%= item.name %></td>
          <td class='item-list-price'><%= item.price %><span>円</span></td>
          <td class='item-list-edit-btn'><%= link_to '編集', edit_item_path(item.id), method: :get %></td>
        </tr>
        <% end %>
      </table>
      <div class='item-add-btn'>
        <%= link_to 'おてつだい追加', new_item_path %>
      </div>
    </div>
  </section>
</div>

app/views/items/new.html.erb
<div class='contents'>
  <section class="contents-section">
    <div class="contents-section-inner">
      <h1 class='page-ttl'><span>おてつだい登録<span></h1>
      <%= form_with model: @item, url: items_path, id: 'new-item', class: 'item-form-wrap', local: true do |f|%>
      <div class='form-wrap'>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">おてつだい項目名</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :name, class: "input-default", id:"item-name", placeholder:"そうじき・おさらふきなど" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">金額(半角)</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='form-input-wrap'>
            <%= f.text_field :price, class: "input-default input-custom", id:"item-price", placeholder:"例）300" %>
            <span class="form-yen">円(えん)</span>
          </div>
        </div>
        <div class="item-save-btn-wrap">
          <%= f.submit "保存する", class: "item-save-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pockeee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@400;500;700;800&amp;display=swap" rel="stylesheet">
  </head>

  <body>
    <header class='header'>
      <div class='header-inner'>
        <h1><%= link_to 'pockeee', "/" %></h1>
        <div class='nav'>
          <ul class='lists-right'>
            <% if user_signed_in? %>
              <li><%= link_to 'おてつだいリスト', items_path, class: "nav-list-btn" %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
              <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class='footer'>
      <div class='footer-contents'>
        <div>
          <h2>pockeee</h2>
          <p>pockeee(ポッケー)は、<br>まいつきの おたのしみの おこづかいと<br>がんばった おてつだいの おだちんを<br>かんりする アプリです。</p>
        </div>
      </div>
      <p class='copylight'>© pockeee</p>
    </footer>
  </body>
</html>

app/views/members/edit.html.erb
<div class='contents'>
  <section class="contents-section">
    <div class="contents-section-inner">
      <h2 class="page-ttl" style='color: <%= @member.color %>;'>
        <span class="member-ttl-name" style="border-bottom: 2px dotted <%= @member.color %>;"><%= @member.name %><span class="member-ttl-name-small">さんの</span>ポッケー編集</span>
      </h2>
      <%= form_with model: @member, id: 'new-member', class: 'member-form-wrap', local: true do |f|%>
      <div class='form-wrap'>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">メンバーの名前(なまえ)</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :name, class: "input-default", id:"member-name", placeholder:"ひろ・花・タックン・mikoなど" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">1ヶ月のおこづかい</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='form-input-wrap'>
            <%= f.text_field :fixed, class: "input-default input-custom", id:"member-fixed", placeholder:"例）300" %>
            <span class="form-yen">円(えん)</span>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">カラー</label>
            <span class="indispensable">必須</span>
          </div>
          <div class="member-color-wrap">
            <label><%= f.radio_button :color, "#ffb2b9" %><span class="member-color-label01">ぴんく</span></label>
            <label><%= f.radio_button :color, "#99dcff" %><span class="member-color-label02">あお</span></label>
            <label><%= f.radio_button :color, "#B38447" %><span class="member-color-label03">ちゃいろ</span></label>
            <label><%= f.radio_button :color, "#b2b2b2" %><span class="member-color-label04">はいいろ</span></label>
          </div>
        </div>
        <div class="form-group">
          <div class="field">
            <div class='form-text-wrap'>
              <label class="form-text">画像</label>
              <span class="indispensable">必須</span>
            </div>
            <div id="previews">
              <div class="preview">
                <%= image_tag @member.image, class: "preview-image" if @member.image.attached? %>
              </div>
            </div>
            <label class="edit-image">ファイルを選択
              <%= f.file_field :image, id:"member-image" %>
            </label>
          </div>
        </div>
        <div class="member-save-btn-wrap">
          <%= f.submit "保存する", class: "member-save-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/members/index.html.erb
<div class='contents'>
  <section class="contents-section">
    <div class="contents-section-inner">
      <h2 class='page-ttl'><span class='member-ttl-name'><%= current_user.family_name %><span class='member-ttl-name-small'>さんちの</span>ポッケーメンバー</span></h2>
      <ul class='member-list-wrap'>
      <% current_user.members.each do |member| %>
        <li class='member-list' style='background-color: <%= member.color %>;'>
          <%= link_to "members/#{member.id}/posts/show" do %>
          <div class='member-img-content'>
            <%= image_tag member.image, class: 'member-img' if member.image.attached? %>
          </div>
          <div class='member-info'>
            <h3 class='member-name'><%= member.name %></h3>
            <p><%= @posts_sum_total %></p>
          </div>
          <% end %>
        </li>
      <% end %>
        <li class='member-list' style='background-color: #ccc;'>
          <%= link_to new_member_path do %>
          <div class='member-img-content'>
            <%= image_tag 'member-add.jpg' %>
          </div>
          <div class='member-info'>
            <h3 class='member-name'>メンバー追加</h3>
          </div>
          <% end %>
        </li>
      </ul>
    </div>
  </section>
</div>

app/views/members/new.html.erb
<div class='contents'>
  <section class="contents-section">
    <div class="contents-section-inner">
      <h1 class='page-ttl'><span>新規メンバー登録<span></h1>
      <%= form_with model: @member, id: 'new-member', class: 'member-form-wrap', local: true do |f|%>
      <div class='form-wrap'>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">メンバーの名前(なまえ)</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :name, class: "input-default", id:"member-name", placeholder:"ひろ・花・タックン・mikoなど" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">1ヶ月のおこづかい(半角)</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='form-input-wrap'>
            <%= f.text_field :fixed, class: "input-default input-custom", id:"member-fixed", placeholder:"例）300" %>
            <span class="form-yen">円(えん)</span>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">カラー</label>
            <span class="indispensable">必須</span>
          </div>
          <div class="member-color-wrap">
            <label><%= f.radio_button :color, "#ffb2b9" %><span class="member-color-label01">ぴんく</span></label>
            <label><%= f.radio_button :color, "#99dcff" %><span class="member-color-label02">あお</span></label>
            <label><%= f.radio_button :color, "#b39c7d" %><span class="member-color-label03">ちゃいろ</span></label>
            <label><%= f.radio_button :color, "#b2b2b2" %><span class="member-color-label04">はいいろ</span></label>
          </div>
        </div>
        <div class="form-group">
          <div class="field">
            <div class='form-text-wrap'>
              <label class="form-text">画像</label>
              <span class="indispensable">必須</span>
            </div>
            <div id="previews"></div>
            <div class="click-upload">
              <%= f.file_field :image, id:"member-image" %>
          </div>
          </div>
        </div>
        <div class="member-save-btn-wrap">
          <%= f.submit "保存する", class: "member-save-btn" %>
        </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/posts/show.html.erb
<div class='contents posts-contents-wrap'>
  <section id='post-list' class='contents-section' >
    <div class="contents-section-inner">
      <div class='post-ttl-wrap'>
        <div class="post-ttl-img"><%= image_tag @member.image %></div>
        <h2 class='page-ttl' style='color: <%= @member.color %>;'>
          <span class="member-ttl-name" style='border-bottom: 2px dotted <%= @member.color %>'><%= @member.name %>のポッケー</span>
        </h2>
      </div>
      <div class='post-sum-wrap' style='background: <%= @member.color %>;'>
        <h3><span class="member-ttl-name" %>\ <%= (@prev_month + 1.month).month %>月のポッケー /</span></h3>
        <div class='post-sum-inner'>
          <div class='post-sum-item post-sum-fixed'>
            <h4>まいつきの<br>おこづかい</h4>
            <p style='color: <%= @member.color %>;'><span><%= @member.fixed %></span><br>えん</p>
          </div>
          <div class='post-sum-item post-sum-sum'>
            
            <h4>おてつだいの<br>おだちん</h4>
            <p style='color: <%= @member.color %>;'><span><%= @posts_sum %></span><br>えん</p>
          </div>
          <div class='post-sum-item post-sum-total'>
            <h4>ごうけい</h4>
            <p style='color: <%= @member.color %>;'><span><%= @posts_sum_total %></span><br>えん</p>
          </div>
        </div>
      </div>
      <ul class='posts-month-wrap'>
        <li><%= link_to "< #{@prev_month.month}月のポッケー" ,member_post_path(month:@prev_month), style: "color: #{@member.color};" %></li>
        <% if Date.today.month == (@next_month - 1.month).month %>
          <li></li>
        <% else %>
          <li><%= link_to "#{(@next_month).month}月のポッケー >" ,member_post_path(month:@next_month), style: "color: #{@member.color};" %></li>
        <% end %>
      </ul>
      
      <table class='item-list-wrap post-list-wrap'>
        <tr>
          <th>ひにち</th>
          <th>おてつだい</th>
          <th>きんがく</th>
          <th>へんしゅう</th>
          <th>さくじょ</th>
        </tr>
        <% if @posts.present? %>
        <% @posts.each do |post| %>
          <tr>
            <td class='item-list-day'><%= post.day %></td>
            <td class='item-list-name'><%= Item.find_by(id: post.item_id).name %></td>
            <td class='item-list-price'><%= Item.find_by(id: post.item_id).price %></td>
            <td class='item-list-edit-btn post-list-edit-btn'><%= link_to 'へんしゅう', "#{post.id}/edit", method: :get ,style: "background: #{@member.color};" %></td>
            <td class='item-list-delete-btn post-list-delete-btn'><%= link_to 'さくじょ', "#{post.id}", method: :delete, data: {confirm: "本当に削除しますか?(ほんとうにさくじょしますか？)"} %></td>
          </tr>
        <% end %>
        <% else %>
        <tr>
          <th>-</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <% end %>
      </table>
    </div>
  </section>
  <%= render "new" %>
  <section id="post-comments" class="contents-section">
    <div class="contents-section-inner">
      <%= render "comments/show" %>
      <div class="comment_more_btn">
        <%= link_to 'コメントをかく・もっとみる', member_comments_path ,style: "background: #{@member.color};" %>
      </div>
    </div>
  </section>
  <section id='post-member' class='contents-section'>
    <div class="contents-section-inner">
      
      <div class='post-member-wrap'>
        <div class="member-detail-img">
          <%= image_tag @member.image, class: 'member-img' %>
        </div>
        <ul class="post-member-list">
          <li>
            <h3 class='post-ttl' style='color: <%= @member.color %>;'>
              <span class="member-ttl-name" style='border-bottom: 2px dotted <%= @member.color %>'><%= @member.name %><span class="member-ttl-name-small">さん</span></span>
            </h3>
          </li>
          <li class='post-member-list-fixed' style='color: <%= @member.color %>;'>まいつきのおこづかい : <span><%= @member.fixed %></span>えん</li>
          <li class='post-member-list-btn'><%= link_to 'メンバーへんしゅう', edit_member_path(@member.id), style: "color: #{@member.color}; border: 2px solid #{@member.color};", method: :get %></li>
      </ul>
      </div>
    </div>
  </section>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='footer'>
  <div class='footer-contents'>
    <div>
      <h2>pockeee</h2>
      <p>pockeee(ポッケー)は、<br>まいつきの おたのしみの おこづかいと<br>がんばった おてつだいの おだちんを<br>かんりする アプリです。</p>
    </div>
  </div>
  <p class='copylight'>© pockeee</p>
</footer>